/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdint.h"
#include "stdlib.h"
#include "stdio.h"

#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_drivers.h"
#include "Stm32_F103C6_EXTI_drivers.h"
#include "LCD.h"
#include "Keypad.h"


uint32_t IRQ_Flag = 0;


void my_wait(int x)
{
	unsigned int i ,j;
	for(i = 0 ; i<x ; i++)
		for(j = 0 ; j<255 ; j++);
}

void EXTI9_Callback(void)
{
	IRQ_Flag = 1;
	LCD_Write_String("IRQ EXTI9 is happened _|- ");
	my_wait(1000);
}

int main(void)
{
	//Enable clock
	RCC_GPIOA_Clk_En();
	RCC_GPIOB_Clk_En();
	RCC_AFIO_Clk_En();

	LCD_Init();
	LCD_Clear_Screen();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_Pin = EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_CFG.Ptr_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1;
    /* Loop forever */
	while(1)
	{
		if(IRQ_Flag)
		{
			LCD_Clear_Screen();
			IRQ_Flag = 0;
		}
	}
}
