/*
 * stm32_F103C6_gpio_driver.h
 *
 *  Created on: Feb 9, 2024
 *      Author: hassan
 */

#ifndef INC_STM32_F103C6_EXTI_DRIVER_H_
#define INC_STM32_F103C6_EXTI_DRIVER_H_

//Includes

#include"stm32f103x6.h"
#include "stm32_F103C6_gpio_driver.h"

typedef struct
{
	uint16_t			EXTI_InputLineNumber;
	GPIO_typedef		*GPIO_PORT;
	uint16_t			 GPIO_PIN;
	uint8_t				 IVT_IRQ_Number;

}EXTI_GPIO_MAPPING_t;



typedef struct
{

	EXTI_GPIO_MAPPING_t EXTI_PIN;		//Specifies External interrupt GPIO mapping
										//This member must be set based on @ref EXTI_define

	uint8_t Trigger_type;				//Specifies which Trigger will be applied (Rising , Falling , Both Rising&Falling)
										//This member must be set based on @ EXTI_Trigger_define

	uint8_t IRQ_EN;						//Enable or Disable the IRQ (this member will affect both IRQ MASK in EXTI  & NVIC Interrupt)
										//This member must be set based on @ref_EXTI_IRQ_define

	void (* PTF_IRQ_Callback)(void);	//Set the C Function which will be called once IRQ occur

}EXTI_PinConfig_t;





//===============================
//Macros Configuration References
//===============================

//EXTI LINES
#define EXTI_0			0
#define EXTI_1			1
#define EXTI_2			2
#define EXTI_3			3
#define EXTI_4			4
#define EXTI_5			5
#define EXTI_6			6
#define EXTI_7			7
#define EXTI_8			8
#define EXTI_9			9
#define EXTI_10			10
#define EXTI_11			11
#define EXTI_12			12
#define EXTI_13			13
#define EXTI_14			14
#define EXTI_15			15


//@ref EXTI_define




//EXTI0
#define EXTI0PA0		(EXTI_GPIO_MAPPING_t){EXTI_0,GPIOA,GPIO_PINS_0,EXTI0_IRQ }
#define EXTI0PB0		(EXTI_GPIO_MAPPING_t){EXTI_0,GPIOB,GPIO_PINS_0,EXTI0_IRQ }
#define EXTI0PC0		(EXTI_GPIO_MAPPING_t){EXTI_0,GPIOC,GPIO_PINS_0,EXTI0_IRQ }
#define EXTI0PD0		(EXTI_GPIO_MAPPING_t){EXTI_0,GPIOD,GPIO_PINS_0,EXTI0_IRQ }


//EXTI1
#define EXTI1PA1		(EXTI_GPIO_MAPPING_t){EXTI_1,GPIOA,GPIO_PINS_1,EXTI1_IRQ }
#define EXTI1PB1		(EXTI_GPIO_MAPPING_t){EXTI_1,GPIOB,GPIO_PINS_1,EXTI1_IRQ }
#define EXTI1PC1		(EXTI_GPIO_MAPPING_t){EXTI_1,GPIOC,GPIO_PINS_1,EXTI1_IRQ }
#define EXTI1PD1		(EXTI_GPIO_MAPPING_t){EXTI_1,GPIOD,GPIO_PINS_1,EXTI1_IRQ }


//EXTI2
#define EXTI2PA2		(EXTI_GPIO_MAPPING_t){EXTI_2,GPIOA,GPIO_PINS_2,EXTI2_IRQ }
#define EXTI2PB2		(EXTI_GPIO_MAPPING_t){EXTI_2,GPIOB,GPIO_PINS_2,EXTI2_IRQ }
#define EXTI2PC2		(EXTI_GPIO_MAPPING_t){EXTI_2,GPIOC,GPIO_PINS_2,EXTI2_IRQ }
#define EXTI2PD2		(EXTI_GPIO_MAPPING_t){EXTI_2,GPIOD,GPIO_PINS_2,EXTI2_IRQ }


//EXTI3
#define EXTI3PA3		(EXTI_GPIO_MAPPING_t){EXTI_3,GPIOA,GPIO_PINS_3,EXTI3_IRQ }
#define EXTI3PB3		(EXTI_GPIO_MAPPING_t){EXTI_3,GPIOB,GPIO_PINS_3,EXTI3_IRQ }
#define EXTI3PC3		(EXTI_GPIO_MAPPING_t){EXTI_3,GPIOC,GPIO_PINS_3,EXTI3_IRQ }
#define EXTI3PD3		(EXTI_GPIO_MAPPING_t){EXTI_3,GPIOD,GPIO_PINS_3,EXTI3_IRQ }


//EXTI4
#define EXTI4PA4		(EXTI_GPIO_MAPPING_t){EXTI_4,GPIOA,GPIO_PINS_4,EXTI4_IRQ }
#define EXTI4PB4		(EXTI_GPIO_MAPPING_t){EXTI_4,GPIOB,GPIO_PINS_4,EXTI4_IRQ }
#define EXTI4PC4		(EXTI_GPIO_MAPPING_t){EXTI_4,GPIOC,GPIO_PINS_4,EXTI4_IRQ }
#define EXTI4PD4		(EXTI_GPIO_MAPPING_t){EXTI_4,GPIOD,GPIO_PINS_4,EXTI4_IRQ }


//EXTI5
#define EXTI5PA5		(EXTI_GPIO_MAPPING_t){EXTI_5,GPIOA,GPIO_PINS_5,EXTI5_IRQ }
#define EXTI5PB5		(EXTI_GPIO_MAPPING_t){EXTI_5,GPIOB,GPIO_PINS_5,EXTI5_IRQ }
#define EXTI5PC5		(EXTI_GPIO_MAPPING_t){EXTI_5,GPIOC,GPIO_PINS_5,EXTI5_IRQ }
#define EXTI5PD5		(EXTI_GPIO_MAPPING_t){EXTI_5,GPIOD,GPIO_PINS_5,EXTI5_IRQ }


//EXTI6
#define EXTI6PA6		(EXTI_GPIO_MAPPING_t){EXTI_6,GPIOA,GPIO_PINS_6,EXTI6_IRQ }
#define EXTI6PB6		(EXTI_GPIO_MAPPING_t){EXTI_6,GPIOB,GPIO_PINS_6,EXTI6_IRQ }
#define EXTI6PC6		(EXTI_GPIO_MAPPING_t){EXTI_6,GPIOC,GPIO_PINS_6,EXTI6_IRQ }
#define EXTI6PD6		(EXTI_GPIO_MAPPING_t){EXTI_6,GPIOD,GPIO_PINS_6,EXTI6_IRQ }


//EXTI7
#define EXTI7PA7		(EXTI_GPIO_MAPPING_t){EXTI_7,GPIOA,GPIO_PINS_7,EXTI7_IRQ }
#define EXTI7PB7		(EXTI_GPIO_MAPPING_t){EXTI_7,GPIOB,GPIO_PINS_7,EXTI7_IRQ }
#define EXTI7PC7		(EXTI_GPIO_MAPPING_t){EXTI_7,GPIOC,GPIO_PINS_7,EXTI7_IRQ }
#define EXTI7PD7		(EXTI_GPIO_MAPPING_t){EXTI_7,GPIOD,GPIO_PINS_7,EXTI7_IRQ }


//EXTI8
#define EXTI8PA8		(EXTI_GPIO_MAPPING_t){EXTI_8,GPIOA,GPIO_PINS_8,EXTI8_IRQ }
#define EXTI8PB8		(EXTI_GPIO_MAPPING_t){EXTI_8,GPIOB,GPIO_PINS_8,EXTI8_IRQ }
#define EXTI8PC8		(EXTI_GPIO_MAPPING_t){EXTI_8,GPIOC,GPIO_PINS_8,EXTI8_IRQ }
#define EXTI8PD8		(EXTI_GPIO_MAPPING_t){EXTI_8,GPIOD,GPIO_PINS_8,EXTI8_IRQ }


//EXTI9
#define EXTI9PA9		(EXTI_GPIO_MAPPING_t){EXTI_9,GPIOA,GPIO_PINS_9,EXTI9_IRQ }
#define EXTI9PB9		(EXTI_GPIO_MAPPING_t){EXTI_9,GPIOB,GPIO_PINS_9,EXTI9_IRQ }
#define EXTI9PC9		(EXTI_GPIO_MAPPING_t){EXTI_9,GPIOC,GPIO_PINS_9,EXTI9_IRQ }
#define EXTI9PD9		(EXTI_GPIO_MAPPING_t){EXTI_9,GPIOD,GPIO_PINS_9,EXTI9_IRQ }


//EXTI10
#define EXTI10PA10		(EXTI_GPIO_MAPPING_t){EXTI_10,GPIOA,GPIO_PINS_10,EXTI10_IRQ }
#define EXTI10PB10		(EXTI_GPIO_MAPPING_t){EXTI_10,GPIOB,GPIO_PINS_10,EXTI10_IRQ }
#define EXTI10PC10		(EXTI_GPIO_MAPPING_t){EXTI_10,GPIOC,GPIO_PINS_10,EXTI10_IRQ }
#define EXTI10PD10		(EXTI_GPIO_MAPPING_t){EXTI_10,GPIOD,GPIO_PINS_10,EXTI10_IRQ }


//EXTI11
#define EXTI11PA11		(EXTI_GPIO_MAPPING_t){EXTI_11,GPIOA,GPIO_PINS_11,EXTI11_IRQ }
#define EXTI11PB11		(EXTI_GPIO_MAPPING_t){EXTI_11,GPIOB,GPIO_PINS_11,EXTI11_IRQ }
#define EXTI11PC11		(EXTI_GPIO_MAPPING_t){EXTI_11,GPIOC,GPIO_PINS_11,EXTI11_IRQ }
#define EXTI11PD11		(EXTI_GPIO_MAPPING_t){EXTI_11,GPIOD,GPIO_PINS_11,EXTI11_IRQ }


//EXTI12
#define EXTI12PA12		(EXTI_GPIO_MAPPING_t){EXTI_12,GPIOA,GPIO_PINS_12,EXTI12_IRQ }
#define EXTI12PB12		(EXTI_GPIO_MAPPING_t){EXTI_12,GPIOB,GPIO_PINS_12,EXTI12_IRQ }
#define EXTI12PC12		(EXTI_GPIO_MAPPING_t){EXTI_12,GPIOC,GPIO_PINS_12,EXTI12_IRQ }
#define EXTI12PD12		(EXTI_GPIO_MAPPING_t){EXTI_12,GPIOD,GPIO_PINS_12,EXTI12_IRQ }


//EXTI13
#define EXTI13PA13		(EXTI_GPIO_MAPPING_t){EXTI_13,GPIOA,GPIO_PINS_13,EXTI13_IRQ }
#define EXTI13PB13		(EXTI_GPIO_MAPPING_t){EXTI_13,GPIOB,GPIO_PINS_13,EXTI13_IRQ }
#define EXTI13PC13		(EXTI_GPIO_MAPPING_t){EXTI_13,GPIOC,GPIO_PINS_13,EXTI13_IRQ }
#define EXTI13PD13		(EXTI_GPIO_MAPPING_t){EXTI_13,GPIOD,GPIO_PINS_13,EXTI13_IRQ }


//EXTI14
#define EXTI14PA14		(EXTI_GPIO_MAPPING_t){EXTI_14,GPIOA,GPIO_PINS_14,EXTI14_IRQ }
#define EXTI14PB14		(EXTI_GPIO_MAPPING_t){EXTI_14,GPIOB,GPIO_PINS_14,EXTI14_IRQ }
#define EXTI14PC14		(EXTI_GPIO_MAPPING_t){EXTI_14,GPIOC,GPIO_PINS_14,EXTI14_IRQ }
#define EXTI14PD14		(EXTI_GPIO_MAPPING_t){EXTI_14,GPIOD,GPIO_PINS_14,EXTI14_IRQ }


//EXTI15
#define EXTI15PA15		(EXTI_GPIO_MAPPING_t){EXTI_15,GPIOA,GPIO_PINS_15,EXTI15_IRQ }
#define EXTI15PB15		(EXTI_GPIO_MAPPING_t){EXTI_15,GPIOB,GPIO_PINS_15,EXTI15_IRQ }
#define EXTI15PC15		(EXTI_GPIO_MAPPING_t){EXTI_15,GPIOC,GPIO_PINS_15,EXTI15_IRQ }
#define EXTI15PD15		(EXTI_GPIO_MAPPING_t){EXTI_15,GPIOD,GPIO_PINS_15,EXTI15_IRQ }



//============================



//@ref EXTI_Trigger_define

#define EXTI_Trigger_Rising						0
#define EXTI_Trigger_Falling					1
#define EXTI_Trigger_Rising_and_Falling			2


//@ref_EXTI_IRQ_define
#define EXTI_IRQ_Enable			1
#define EXTI_IRQ_Disable		0






/*
 * =================================================================================
 *
 * 							APIs Supported by "MCAL GPIO DRIVER"
 *
 * =================================================================================
 *
 */

	void MCAL_EXTI_GPIO_Init (EXTI_PinConfig_t* EXTI_Config);
	void MCAL_EXTI_GPIO_Deinit (void);
	void MCAL_EXTI_GPIO_Update (EXTI_PinConfig_t* EXTI_Config);




#endif /* INC_STM32_F103C6_EXTI_DRIVER_H_ */
